// Shared grading constants ported from grade_engine.py.
// Keep values identical to the Python source.

import type { GradeLetter, Sport } from './grade-types.ts'

export type GradingThreshold = readonly [number, GradeLetter]

export const GRADE_THRESHOLDS: readonly GradingThreshold[] = [
  [8.0, 'A+'],
  [7.3, 'A'],
  [6.5, 'A-'],
  [6.0, 'B+'],
  [5.5, 'B'],
  [5.0, 'B-'],
  [4.5, 'C+'],
  [3.5, 'C'],
  [2.5, 'D'],
  [0.0, 'F'],
] as const

export const SIZING_MAP: Record<string, string> = {
  'A+': '2u',
  'A': '1.5u',
  'A-': '1u',
  'B+': '1u',
  'B': 'PASS',
  'B-': 'PASS',
  'C+': 'PASS',
  'C': 'PASS',
  'D': 'PASS',
  'F': 'PASS',
}

export const CHAIN_CAP = 2.0

// Hardcoded elite/good NHL goalies — fallback when SV% data is not available.
// Names lowercased for matching; check by last name.
export const ELITE_NHL_GOALIES = new Set<string>([
  'hellebuyck',
  'sorokin',
  'vasilevskiy',
  'shesterkin',
  'bobrovsky',
  'saros',
  'markstrom',
  'oettinger',
  'hill',
  'kuemper',
  'swayman',
  'ullmark',
  'skinner',
  'demko',
  'hart',
  'gibson',
  'talbot',
  'stolarz',
])

export const GOOD_NHL_GOALIES = new Set<string>([
  'andersen',
  'husso',
  'husarek',
  'mrazek',
  'binnington',
  'georgiev',
  'jarry',
  'blackwood',
  'vanecek',
  'lyon',
  'merzlikins',
  'kahkonen',
  'wedgewood',
  'samsonov',
  'knight',
  'varlamov',
  'luukkonen',
])

export interface ChainDef {
  readonly bonus: number
  readonly sports: readonly Sport[] | null
}

export const CHAINS = {
  // Positive chains (+bonus)
  THE_MISPRICING: { bonus: 1.0, sports: null },
  FATIGUE_FADE: { bonus: 0.8, sports: null },
  FORM_WAVE: { bonus: 0.7, sports: null },
  INJURY_GOLDMINE: { bonus: 0.8, sports: null },
  REST_DOMINATION: { bonus: 0.7, sports: null },
  SHARPS_LOVE: { bonus: 0.8, sports: null },
  BLOWOUT_INCOMING: { bonus: 0.7, sports: ['NBA', 'NCAAB'] },
  MISMATCH_MASSACRE: { bonus: 0.8, sports: null },
  ROAD_WARRIOR: { bonus: 0.6, sports: null },
  BENCH_MOB: { bonus: 0.5, sports: null },
  REVENGE_GAME: { bonus: 0.5, sports: null },
  BOUNCE_BACK: { bonus: 0.5, sports: null },
  HUNGRY_DOG: { bonus: 0.6, sports: null },
  // Negative chains (-penalty)
  DUMPSTER_FIRE: { bonus: -1.0, sports: null },
  COLD_TAKE: { bonus: -0.7, sports: null },
  GLASS_CANNON: { bonus: -0.5, sports: null },
  SCHEDULE_LOSS: { bonus: -0.7, sports: null },
  THIN_ROSTER: { bonus: -0.6, sports: null },
  COASTING_FAV: { bonus: -0.5, sports: null },
  FADE_THE_STREAK: { bonus: -0.5, sports: null },
  // Sport-specific
  GOALIE_EDGE: { bonus: 0.7, sports: ['NHL'] },
  GOALIE_WORKLOAD_WALL: { bonus: -0.7, sports: ['NHL'] },
  SPECIAL_TEAMS_EDGE: { bonus: 0.7, sports: ['NHL'] },
  B2B_BLEED: { bonus: -0.7, sports: ['NHL'] },
  SHOT_QUALITY_SURGE: { bonus: 0.6, sports: ['NHL'] },
  BACKUP_MISMATCH: { bonus: 0.6, sports: ['NHL'] },
  SPECIAL_TEAMS_VOID: { bonus: -0.6, sports: ['NHL'] },
  ALTITUDE_ICE: { bonus: -0.5, sports: ['NHL'] },
  BULLPEN_LOCKDOWN: { bonus: 0.8, sports: ['MLB'] },
  BULLPEN_FATIGUE_CASCADE: { bonus: -0.7, sports: ['MLB'] },
  POWER_FLYBALL_OVER: { bonus: 0.7, sports: ['MLB'] },
  CONTACT_PRESSURE: { bonus: 0.5, sports: ['MLB'] },
  GROUNDBALL_DUEL: { bonus: -0.6, sports: ['MLB'] },
  COORS_ACTUAL: { bonus: 0.9, sports: ['MLB'] },
  ACE_ISOLATION_TRAP: { bonus: -0.6, sports: ['MLB'] },
  PLATOON_EXPLOIT: { bonus: 0.6, sports: ['MLB'] },
  FIVE_AND_DIVE: { bonus: 0.5, sports: ['MLB'] },
  WEATHER_WIND_BOOST: { bonus: 0.6, sports: ['MLB'] },
  CONGESTION_FADE: { bonus: 0.8, sports: ['SOCCER'] },
  CLASS_GAP: { bonus: 0.7, sports: ['SOCCER'] },
  FORTRESS_HOME: { bonus: 0.6, sports: ['SOCCER'] },
  TOURIST_TRAP: { bonus: -0.6, sports: ['SOCCER'] },
  DERBY_CHAOS: { bonus: 0.5, sports: ['SOCCER'] },
  KEEPER_WALL: { bonus: 0.6, sports: ['SOCCER'] },
  ROTATION_RISK: { bonus: -0.6, sports: ['SOCCER'] },
  XG_REGRESSION: { bonus: 0.5, sports: ['SOCCER'] },
  SET_PIECE_THREAT: { bonus: 0.4, sports: ['SOCCER'] },
  EUROPEAN_HANGOVER: { bonus: -0.5, sports: ['SOCCER'] },
  LEAGUE_FORTRESS: { bonus: 0.5, sports: ['SOCCER'] },
  AWAY_DAY_FADE: { bonus: -0.5, sports: ['SOCCER'] },
  BLUE_BLOOD_TRAP: { bonus: -0.5, sports: ['NCAAB'] },
  MARCH_MADNESS_UPSET: { bonus: -0.6, sports: ['NCAAB'] },
  TEMPO_TRAP: { bonus: 0.5, sports: ['NCAAB'] },
  CONFERENCE_MISMATCH: { bonus: 0.6, sports: ['NCAAB'] },
  HOME_COURT_CAULDRON: { bonus: 0.5, sports: ['NCAAB'] },
  DEPTH_DRAIN: { bonus: -0.5, sports: ['NCAAB'] },
  TOURNAMENT_PEDIGREE: { bonus: 0.4, sports: ['NCAAB'] },
  THREE_POINT_STORM: { bonus: 0.7, sports: ['NBA'] },
  B2B_CORPSE: { bonus: -0.8, sports: ['NBA'] },
  ALTITUDE_BLEED: { bonus: -0.6, sports: ['NBA'] },
  PACE_MISMATCH: { bonus: 0.6, sports: ['NBA'] },
  LOAD_MANAGEMENT_ARB: { bonus: 0.5, sports: ['NBA'] },
  CLUTCH_LOCK: { bonus: 0.5, sports: ['NBA'] },
  TURNOVER_PRESSURE: { bonus: 0.5, sports: ['NBA'] },
  REF_PACE_BOOST: { bonus: 0.4, sports: ['NBA'] },
  WEATHER_FADE: { bonus: -0.7, sports: ['NFL'] },
  DOME_TEAM_FREEZE: { bonus: -0.6, sports: ['NFL'] },
  DIVISIONAL_DOGFIGHT: { bonus: 0.5, sports: ['NFL'] },
  TURNOVER_MACHINE: { bonus: 0.7, sports: ['NFL'] },
  RED_ZONE_HAMMER: { bonus: 0.6, sports: ['NFL'] },
  PRIMETIME_LETDOWN: { bonus: -0.5, sports: ['NFL'] },
  QB_WEATHER_EDGE: { bonus: 0.6, sports: ['NFL'] },
  GROUND_AND_POUND: { bonus: 0.5, sports: ['NFL'] },
  COACHING_MISMATCH: { bonus: 0.5, sports: ['NFL'] },
  SCHEDULE_TRAP: { bonus: -0.6, sports: ['NFL'] },
  RECRUITING_GAP: { bonus: 0.7, sports: ['NCAAF'] },
  HOME_FORTRESS_CFB: { bonus: 0.6, sports: ['NCAAF'] },
  COACHING_CHAOS: { bonus: -0.6, sports: ['NCAAF'] },
  RIVALRY_UPSET: { bonus: 0.5, sports: ['NCAAF'] },
  PORTAL_FLUX: { bonus: -0.5, sports: ['NCAAF'] },
  // MMA chains
  REACH_STRIKER: { bonus: 0.6, sports: ['MMA'] },
  GRAPPLER_TRAP: { bonus: 0.5, sports: ['MMA'] },
  CAMP_EDGE: { bonus: 0.4, sports: ['MMA'] },
  FINISH_THREAT: { bonus: 0.5, sports: ['MMA'] },
  RING_RUST: { bonus: -0.5, sports: ['MMA'] },
  // Boxing chains
  REACH_KING: { bonus: 0.7, sports: ['BOXING'] },
  SOUTHPAW_ANGLE: { bonus: 0.5, sports: ['BOXING'] },
  RING_RUST_BOX: { bonus: -0.6, sports: ['BOXING'] },
  KO_ARTIST: { bonus: 0.5, sports: ['BOXING'] },
} as const satisfies Record<string, ChainDef>

export const SPORT_VARIABLES: Record<Sport, Record<string, number>> = {
  NBA: {
    star_player: 9,
    rest: 9,
    off_ranking: 8,
    def_ranking: 8,
    pace: 7,
    form: 7,
    road_trip: 7,
    h2h: 6,
    ats: 6,
    line_movement: 5,
    home_away: 5,
    depth: 4,
    motivation: 5,
    late_game_strength: 7,
    quarter_pace: 6,
    bench_diff: 6,
    three_pt_rate: 8,
    b2b_fatigue: 8,
    travel_distance: 6,
    altitude: 7,
    referee_pace: 5,
    turnover_rate: 6,
  },
  NHL: {
    // Tier 1: Goalie is king (consensus: 77% models cite goalie metrics)
    goalie: 10.8,
    goalie_workload: 9.7,
    goalie_tier_delta: 9.2,
    // Tier 2: Team strength + possession (58% cite xG/Corsi)
    off_ranking: 8.9,
    def_ranking: 8.6,
    scoring_margin_diff: 8.3,
    star_player: 8.1,
    // Tier 3: Special teams + situational
    pp_pct: 7.9,
    pk_pct: 7.5,
    special_teams_combined: 7.3,
    rest: 7.7,
    b2b_flag: 7.1,
    form: 6.9,
    // Tier 4: Matchup + context
    home_away_split: 6.7,
    road_trip: 6.5,
    travel_fatigue: 6.3,
    h2h: 6.1,
    depth: 5.9,
    schedule_density: 5.7,
    shot_quality: 5.5,
    altitude: 5.3,
    // Tier 5: Market + situational
    ats: 5.1,
    line_movement: 4.9,
    motivation: 4.7,
    league_position_gap: 4.5,
    record_strength: 4.3,
    run_differential_l5: 4.1,
    home_away: 3.9,
  },
  MLB: {
    // Tier 1: Bullpen is king + K matchup thesis (Peter's philosophy)
    bullpen: 10.9,
    bullpen_k_dominance: 10.4,
    k_rate_vs_barrel: 9.8,
    bullpen_fatigue: 9.5,
    // Tier 2: Lineup quality + starter depth (NOT starter name)
    lineup_vs_hand: 9.2,
    starter_depth: 8.9,
    lineup_dna: 8.6,
    pitcher_hitter_archetype: 8.3,
    // Tier 3: Offensive/defensive strength
    off_ranking: 8.1,
    def_ranking: 7.9,
    scoring_margin_diff: 7.7,
    plate_discipline: 7.5,
    star_player: 7.3,
    // Tier 4: Pitcher detail + matchup depth
    pitcher_profile: 7.1,
    starting_pitcher: 6.9,
    bullpen_sequencing: 6.7,
    platoon_depth: 6.5,
    pitcher_fatigue: 6.3,
    // Tier 5: Context + environment
    park_factor: 6.1,
    weather_factor: 5.9,
    umpire: 5.7,
    gb_fb_ratio: 5.5,
    form: 5.3,
    run_environment: 5.1,
    // Tier 6: Situational + market
    home_away_split: 4.9,
    rest: 4.7,
    h2h: 4.5,
    run_differential_l5: 4.3,
    record_strength: 4.1,
    ats: 3.9,
    line_movement: 3.7,
    home_away: 3.5,
    depth: 3.3,
    motivation: 3.1,
    manager_tendencies: 2.9,
    schedule_density: 2.7,
  },
  SOCCER: {
    congestion: 6,
    form: 8,
    star_player: 8,
    off_ranking: 9,
    def_ranking: 9,
    home_away: 7,
    rest: 4,
    h2h: 6,
    motivation: 6,
    ats: 6,
    line_movement: 6,
    depth: 4,
    goalkeeper: 8,
    squad_rotation: 6,
    league_home_boost: 5,
  },
  NCAAB: {
    off_ranking: 9,
    def_ranking: 9,
    star_player: 9,
    line_movement: 9,
    pace: 8,
    ats: 8,
    conference_strength: 8,
    form: 7,
    tempo_real: 7,
    h2h: 6,
    home_away: 6,
    depth: 7,
    motivation: 6,
    tournament_exp: 6,
    rest: 5,
  },
  NFL: {
    off_ranking: 9,
    def_ranking: 9,
    star_player: 8,
    form: 8,
    home_away: 7,
    rest: 7,
    pace: 7,
    weather: 7,
    turnover_diff: 7,
    h2h: 6,
    ats: 7,
    red_zone: 6,
    divisional: 6,
    line_movement: 6,
    motivation: 6,
    depth: 5,
    coaching: 5,
  },
  NCAAF: {
    off_ranking: 9,
    def_ranking: 9,
    star_player: 8,
    form: 8,
    home_away: 8,
    rest: 6,
    h2h: 5,
    ats: 7,
    line_movement: 7,
    motivation: 7,
    depth: 5,
    pace: 7,
    recruiting: 7,
    coaching_change: 6,
  },
  MMA: {
    form: 9,
    reach_advantage: 8,
    star_player: 7,
    motivation: 7,
    finish_rate: 7,
    rest: 5,
    h2h: 5,
    line_movement: 5,
  },
  BOXING: {
    form: 9,
    reach_advantage: 8,
    star_player: 7,
    motivation: 7,
    stance_matchup: 6,
    finish_rate: 6,
    rest: 5,
    h2h: 5,
    line_movement: 5,
  },
  WNBA: {
    off_ranking: 9,
    def_ranking: 9,
    star_player: 10,
    form: 8,
    line_movement: 7,
    h2h: 6,
    ats: 7,
    home_away: 4,
    rest: 5,
    depth: 8,
    motivation: 6,
    three_pt_rate: 5,
    b2b_fatigue: 4,
    travel_distance: 7,
    altitude: 3,
    bench_diff: 7,
    turnover_rate: 6,
  },
  TENNIS: {
    surface_edge: 10,
    form: 9,
    h2h: 8,
    serve_dominance: 9,
    return_game: 8,
    ranking_gap: 7,
    fatigue: 8,
    mental_clutch: 7,
    star_player: 6,
    weather_factor: 5,
    home_away: 3,
    line_movement: 6,
    ats: 5,
    motivation: 7,
  },
  COLLEGE_BASEBALL: {
    starting_pitcher: 10,
    bullpen: 6,
    off_ranking: 8,
    def_ranking: 7,
    form: 8,
    home_away: 7,
    weather_factor: 7,
    h2h: 5,
    ats: 5,
    conference_strength: 7,
    ranking_gap: 6,
    rest: 5,
    line_movement: 5,
    motivation: 6,
    star_player: 7,
    depth: 4,
  },
}
